{
    'name': 'Education Management System',
    'version': '19.0.4.7.0',
    'category': 'Education',
    'summary': 'Complete school and college management - admissions, classes, attendance, fees, transport',
    'author': 'Tori Solutions Ltd',
    'depends': [
        'base', 'mail', 'portal', 'website', 'account', 'hr', 'web', 'base_automation',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/mail_templates.xml',
        'data/bd_location_data.xml',
        'data/application_stage_data.xml',
        'data/application_stage_backfill.xml',
        'views/menus.xml',
        'views/session_views.xml',
        'views/grade_scale_views.xml',
        'views/class_views.xml',
        'views/timetable_views.xml',
        'views/application_stage_views.xml',
        'views/admission_views.xml',
        'views/enrollment_views.xml',
        'views/attendance_views.xml',
        'views/assignment_views.xml',
        'views/fee_views.xml',
        'views/scholarship_views.xml',
        'views/library_views.xml',
        'views/transport_views.xml',
        'views/lesson_views.xml',
        'views/discipline_views.xml',
        'views/announcement_views.xml',
        'views/community_service_views.xml',
        'views/id_card_views.xml',
        'views/dashboard_views.xml',
        'views/integration_views.xml',
        'views/feature_menus.xml',
        'report/fee_slip_template.xml',
        'report/marksheet_template.xml',
        'report/transcript_template.xml',
        'report/id_card_template.xml',
        'report/application_template.xml',
        'website/templates/admission_form.xml',
        'website/templates/portal_templates.xml',
        'website/templates/portal_navigation.xml',
        'website/website_pages.xml',
    ],
    'demo': [
        'data/test_assets.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'tori_school_management/static/src/js/barcode_attendance.js',
            'tori_school_management/static/src/js/dashboard.js',
            'tori_school_management/static/src/xml/dashboard.xml',
            'tori_school_management/static/src/css/backend_dashboard.css',
        ],
        'web.assets_frontend': [
            'tori_school_management/static/src/css/portal_styles.css',
        ],
    },
    'uninstall_hook': 'uninstall_hook',
    'application': True,
    'installable': True,
    'license': 'OPL-1',
}

