from . import session
from . import dashboard
from . import grade_scale
from . import class_subject
from . import location_bd
from . import application_stage
from . import timetable
from . import admission
from . import enrollment
from . import attendance
from . import lesson
from . import assignment
from . import marksheet
from . import fee
from . import scholarship
from . import library
from . import transport
from . import id_card
from . import discipline
from . import community_service
from . import announcement

from . import integration
